CREATE TABLE IF NOT EXISTS employees (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	position VARCHAR(255) NOT NULL,
	salary INTEGER NOT NULL,
	hired_date DATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP
);