CREATE TABLE employees (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    salary DOUBLE PRECISION NOT NULL,
    hired_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);