// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Position  string           `json:"position"`
	Salary    float64          `json:"salary"`
	HiredDate pgtype.Date      `json:"hired_date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
